# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV['DATABASE_POOL'] || 5 %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USER'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'moviepicks_development' %>

test:
  <<: *default
  database: moviepicks_test

production:
  <<: *default
  database: centrl_test
